spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/tarefa-db
    username: postgres
    password: Sen@c2023
    driver-class-name: org.postgresql.Driver
